version: 2

models:
  - name: src_region
    columns:
      - name: region_key
        tests:
          - unique:
              tags: ['critical']
          - not_null

  - name: src_nation
    columns:
      - name: nation_key
        tests:
          - unique:
              tags: ['primary_key']
          - not_null

      - name: region_key
        tests:
          - relationships:
              to: ref('src_region')
              field: region_key

  - name: src_part
    columns:
      - name: part_key
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: manufacturer_name
        tests:
          - not_null

  - name: src_supplier
    columns:
      - name: supplier_key
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: nation_key
        tests:
          - relationships:
              to: ref('src_nation')
              field: nation_key

  - name: src_partsupp
    columns:
      - name: part_key
        tests:
          - relationships:
              to: ref('src_part')
              field: part_key
      - name: supplier_key
        tests:
          - relationships:
              to: ref('src_supplier')
              field: supplier_key

  - name: src_customer
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: nation_key
        tests:
          - relationships:
              to: ref('src_nation')
              field: nation_key

  - name: src_orders
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: customer_key
        tests:
          - relationships:
              to: ref('src_customer')
              field: customer_key

  - name: src_lineitem
    columns:
      - name: order_key
        tests:
          - relationships:
              to: ref('src_orders')
              field: order_key
      - name: part_key
        tests:
          - relationships:
              to: ref('src_part')
              field: part_key
      - name: supplier_key
        tests:
          - relationships:
              to: ref('src_supplier')
              field: supplier_key

  - name: fct_lineitem
    description: The fact table with grain = lineitem, Use for analysis when you want to access line item details
    columns:
      - name: lineitem_key
        tests:
          - unique
          - not_null
      - name: order_key
        tests:
          - relationships:
              to: ref('fct_orders')
              field: order_key
          - not_null
      - name: part_key
        tests:
          - relationships:
              to: ref('dim_part')    
              field: part_key
          - not_null
      - name: supplier_key
        tests:
          - relationships:
              to: ref('dim_supplier')
              field: supplier_key
          - not_null

      - name: order_date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
          - not_null
      - name: ship_date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: commit_date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: receipt_date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key

  - name: fct_orders
    description: the fact table with grain = order and aggregated line‐item metrics.
    columns:

      - name: order_key
        description: Surrogate key for each orders
        tests:
          - unique
          - not_null

      - name: customer_key
        description: FK to the customer dimension
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_key
          - not_null

      - name: date_key
        description: FK to the date dimension (order date)
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
          - not_null

  - name: dim_customer
    description: a dimension talbe showing customer attributes
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null

  - name: dim_part
    columns:
      - name: part_key
        tests:
          - unique
          - not_null

  - name: dim_supplier
    description: '{{ doc("some_words_about_dim_suppliers") }}'
    columns:
      - name: supplier_key
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null
  - name: lineitem
    columns:
      - name: discount
        tests:
        - col_max_threshold:
            threshold: 2
            severity: warn
