version: 1

models:
  - name: src_region
    columns:

     - name: region_key
       tests:
         - unique
         - not_null
  - name: src_nation
    columns:
    - name: nation_key
      tests:
        - unique
        - not_null
    - name: region_key
      tests:
        - relationships:
              to: ref('nation')
              field: region_key
  - name: src_part
    columns:
    - name: part_key
    tests:
      - unique
      - not_null

  - name: src_part
    columns:
      - name: part_key
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: manufacturer_name
        tests:
          - not_null

  - name: src_supplier
    columns:
      - name: supplier_key
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: nation_key
        tests:
          - not_null
  - name: src_partsupp
    columns:
      - name: part_key
        tests:
          - not_null
      - name: supplier_key
        tests:
          - not_null

  - name: src_customer
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null
      - name: nation_key
        tests:
          - not_null

  - name: src_orders
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('src_customer')
              field: customer_key

  - name: src_lineitem
    columns:
      - name: order_key
        tests:
          - not_null
          - relationships:
              to: ref('src_orders')
              field: order_key

      - name: part_key
        tests:
          - not_null
          - relationships:
              to: ref('src_part')
              field: part_key

      - name: supplier_key
        tests:
          - not_null
          - relationships:
              to: ref('src_supplier')
              field: supplier_key