\connect bearwulf;
CREATE SCHEMA IF NOT EXISTS landing_zone AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS bronze AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS silver AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS gold AUTHORIZATION admin;
