\connect bearwulf;
DROP SCHEMA IF EXISTS landing_zone CASCADE;
DROP SCHEMA IF EXISTS bronze CASCADE;
DROP SCHEMA IF EXISTS silver CASCADE;
DROP SCHEMA IF EXISTS marts CASCADE;

CREATE SCHEMA IF NOT EXISTS landing_zone AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS bronze AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS silver AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS gold AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS marts AUTHORIZATION admin;
