# Show all tables in all schemas (using local psql)
show-all-tables:
    @PGPASSWORD=pgadmin_bear psql -h localhost -p 5435 -U admin -d bearwulf -c "SELECT schemaname AS schema, tablename AS table FROM pg_tables WHERE schemaname NOT IN ('pg_catalog', 'information_schema') ORDER BY schemaname, tablename;"